### PR TITLE
Update gdnative doc

### PR DESCRIPTION
**Pull request by dianegolfouse**
Bring back automatic documentation and test generation ✊

### CODE REVIEW

**Comment by dianegolfouse** [comment]
Some hypothetical changes to this pr that may be desirable, in case there are things I failed to consider:
1. Remove the last commit: do not move tests from `Test_dijsktra.gd` to `lib.rs`'s documentation (in case automatic generation fails).
2. ~~Do not update the linux executable (it wasn't working properly for me so I rebuilt it).~~
3. Do not mark `Interface::new` as `pub`. This doesn't change anything I think, and making it private would prevent gdnative-doc from generating its documentation 😕.

Those are just things I thought would be worth thinking about, but the current pr seems pretty good to me.

**Comment by dianegolfouse** [comment]
Also, note that some text was automatically removed from `Gut.tscn`.
<details><summary>show</summary>

```
__meta__ = {
"_edit_use_anchors_": false
}
```
</details>

I don't know what that was for, but everything still works so 🤷

**Comment by dianegolfouse** [comment]
Following a discussion with @astrale-sharp, I did *not* update the linux shared library, as this will require more thought. I opened an issue about it at #114 .

**Comment by astrale-sharp** [comment]
Merging this (because you're my friend)

**Comment by dianegolfouse** [comment]
❤️

**Pull request merged**
