### PR TITLE
Update gdnative to 0.9.0.

### PR DESCRIPTION
**Pull request by Zax37**
Hey,

I tried to build the library for Android and updated gdnative version in the process (while learning a bit of Rust :)).
I've faced some issues in `duplicate_graph_from` and bmp handling inside `add_grid_internal` and commented them out.
Besides that, library is still building and working as supposed on PC, but I didn't manage to link it for android platforms.

I'm leaving all changes I've done so far, maybe someone here will be able to push it forward.
If not, I'll probably just reimplement what I need in gdscript, as I already spent on this more time then it will probably take to do so.

Best regards :)

### CODE REVIEW

**Comment by MatejSloboda** [comment]
Hello!

Thank you very much for porting this to "0.9.0". I will review the changes tomorrow, to double check everything works and then hopefully merge it.

The 'duplicate_graph_from' method got broken, because in "0.9.0" they completely changed how you access NativeScript instances (and for the better, from what I've seen). I will try to fix it tomorrow.

I'm not sure why 'add_grid_internal' is broken. Unfortunately, that means 'add_hexagonal_grid' and 'add_square_grid' are broken too. Fortunately, they are just convenience methods, non-essential to the main functionality. Their behavior can easily be replicated externally in GDScript, using the 'add_point' and 'connect_points' methods.

Sorry you weren't able to link it to Android. I'm not sure if it's because of code on our end, or because exporting Godot rust to Android is [rather complicated](https://godot-rust.github.io/book/exporting/android.html).

**Comment by Zax37** [comment]
Hey,

good to see you're still interested in updating the project! I'm pretty sure the problem with Android linking is on my side (something with environment setup), since I wasn't able to link even simple hello world code. Maybe I'll try to check that again later, on another device, but I've already spent couple of days digging through that really hard so I need a break :P I'd appreciate if you could also check, since the build errors are fixed, at least without the two parts I mentioned, but I'll understand if you won't have time for this.

**Comment by MatejSloboda** [comment]
I apologize for the delay. I have been very busy with IRL stuff lately. It may take a few days before get around reviewing this.

**Review by astrale-sharp — CHANGES_REQUESTED** [review]
Hey there :)
glad to see some action on this repository, i was planning myself to port this to gdnative 0.9

seeing you're already on that track, i suggest using
`use gdnative::prelude::*` for simplicity's sake

**Comment by astrale-sharp** [comment]
I say we merge this into master, declare master unstable and advise advise to use the branch v1 for now until everything is fixed.

**Comment by MatejSloboda** [comment]
Agreed!

**Pull request merged**
