### PR TITLE
Setup actions

### PR DESCRIPTION
**Pull request by dianegolfouse**
This leverage github actions to automatically build and test the library on all 3 major platforms (linux, windows and macos).

In theory the files included in this pull request are enough to make everything just work :tm: : we just need to launch the "Build shared libraries" action.

# Pros

- We would be cross-platform ! :smile: 
- Easy to run on all three platforms, github takes care of everything
- Easy to add new compilation targets

# Cons

- The build on windows is kind of a hack (see "Add a 'Build shared libraries' Github action" commit)
- Maybe not very environment-friendly (runs heavy workloads across the internet...). I couldn't really find data on this, but I assume we won't be using it a lot anyways, so this should not be that bad.
- Maybe you prefer another workflow :slightly_smiling_face: 

## Notes

- I could not make the tests work on windows. This is due to some issue with clang rather than our library having a problem, but this is kind of sad nonetheless :slightly_frowning_face: 
- I tried to find a workflow that would be easy to work with, but of course modification can be made (for example, what commit message is made on "Build shared libraries").
- I don't know how to use the godot asset store with/in parallel to this.

### CODE REVIEW

**Comment by dianegolfouse** [comment]
Note that it also may be possible to simply build locally on our machines as an alternative. However :
- Building for macos requires the Apple SDK, which is not exactly easy to get (you need an Apple account, etc...)
- I think this is less maintainable
- You can't run tests for other platforms this way

**Comment by MatejSloboda** [comment]
This is great! Thanks! I'm a little worried about the windows auto-build. GNU and MSVC compilers are compatible on paper, but often not in practice, so hopefully this won't cause issues. I will update the godot asset store entry, since the[ commit that is linked there now apparently has bugs.](https://github.com/MatejSloboda/Dijkstra_map_for_Godot/issues/82)

**Comment by dianegolfouse** [comment]
Yeah, it crossed my mind as well... I tested the produced library on a windows computer and everything seems to work fine for now. I will continue to search for a way to build it directly on windows though.

**Comment by MatejSloboda** [comment]
If necessary, I can compile the windows binaries manually. Also, should we add 32bit targets?
Also, how do I operate this thing? I'm not very well versed in github. Do I just go to the "actions->build->shared libraries-> run workflow"?

**Comment by dianegolfouse** [comment]
Yep, that's it :slightly_smiling_face: 
It will create a new commit, as well as a tag named after the version number chosen. You should also be asked for a description for the commit.
If this is not the behavior you want, the `.github/workflows/make_release.yml` file can be changed.

**Comment by dianegolfouse** [comment]
I will investigate 32bit too... but later ^^

**Pull request merged**
